# Generated by Django 5.1.2 on 2025-03-28 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_cryptotransaction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[("STOCK", "Stock"), ("CRYPTO", "Cryptocurrency")],
                        max_length=6,
                    ),
                ),
                ("ticker", models.CharField(max_length=10)),
                ("price_target", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "trigger_condition",
                    models.CharField(
                        choices=[
                            ("ABOVE", "Price Above Target"),
                            ("BELOW", "Price Below Target"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
